name: Basic compilation checks

on: [pull_request, workflow_dispatch]
#on: [push, pull_request, workflow_dispatch]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: make
      run: make
    - name: make clean
      run: make clean
    - name: make fclean
      run: make fclean
    - name: make re
      run: make re
    - name: Test CMake
      run: |
        cmake .
        make clean
        make
  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: make
      run: make
    - name: make clean
      run: make clean
    - name: make fclean
      run: make fclean
    - name: make re
      run: make re
    - name: Test CMake
      run: |
        cmake .
        make clean
        make
