name: Linux

on: [pull_request, workflow_dispatch]
#on: [push, pull_request, workflow_dispatch]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

# norminette rules
#    - name: Norme check make
#      run: make
#
#    - name: Norme check make clean
#      run: make clean
#
#    - name: Norme check make fclean
#      run: make fclean
#
#    - name: Norme check make re
#      run: make re

    - name: Compilation check
      run: |
        cmake .
        make clean
        make
