name: Systemtests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: Run Systemtests (Linux)

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2

    - name: Run all systemtests
      run: |
        ./tests/stresstest 1
  osx:
    runs-on: macos-latest
    name: Run Systemtests (OSx)

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2

    - name: Run all systemtests
      run: |
        ./tests/stresstest 1
