name: Unittests

#on: [pull_request, workflow_dispatch]
#on: [push, pull_request, workflow_dispatch]

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: Run Catch2 unittests

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
# submodule retreival here should be removed when harou24/libhashmap#2 is merged (anonymous access)
      with:
        submodules: recursive

    - name: Run all unittests
      run: |
        cmake .
        make
        ctest --output-on-failure .
